title: 江世杰的个人博客 - MovingJ
email: moving_j@aliyun.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Moving J # add your name
author-pic: movingj.png
author-qrcode: movingj-qrcode.png
about-author: 我叫江世杰，来自中国广州，全栈工程师，热爱研究新技术，目前主要倾向前端技术，帮助企业建站，微信小程序开发。

# Contact links
email: moving_j@aliyun.com
phone: # Add your Phone number
wechat: mov1ng
website: # Add your website, do not add http://
weibo: https://weibo.com/m0ving
linkedin: movingj 
github: movingj
twitter: '@artemsheludko_' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tagging

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
destination: docs


tag_page_layout: tag
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag

